title: Last Player Picked
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Fantasy Baseball with Mays Copeland
baseurl: ""
url: "https://lastplayerpicked.com"
twitter_username: mayscopeland
github_username:  mayscopeland

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /articles/:title.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
